### ISSUE TITLE
Issue regarding video download on android device from SMB share present on windows machine.

### ISSUE THREAD

**Issue by kheravarun08** [bodaghialib4/react-native-smb#3]
Hi,
Thanks for the great library.
I am able to download images from smb share but when I try to download a video file to android device I am not able to do it.
Initially it starts downloading successfully but after some progress it gives cancel download error

Please find the logs here :

 download data (callback): {"message":"download initialized successfully!!! ","errorCode":"0000","success":true,"destPath":"/data/data/com.smb3project/cache/ch1_video_01.mp4","toPath":"/data/data/com.smb3project/cache/","fromPath":"05262020_142454/","fileName":"ch1_video_01.mp4","downloadId":"976c","clientId":"0b0d","name":"download"}
[Sat May 30 2020 01:38:46.425]  LOG      download data (on download): {"message":"download initialized successfully!!! ","errorCode":"0000","success":true,"destPath":"/data/data/com.smb3project/cache/ch1_video_01.mp4","toPath":"/data/data/com.smb3project/cache/","fromPath":"05262020_142454/","fileName":"ch1_video_01.mp4","downloadId":"976c","clientId":"0b0d","name":"download"}
[Sat May 30 2020 01:38:47.186]  LOG      download progress data (on downloadProgress): {"downloadedSize":"102400","totalSize":"37793367","destPath":"/data/data/com.smb3project/cache/ch1_video_01.mp4","srcPath":"\\\\10.117.82.110\\fun2\\05262020_142454/","fileName":"ch1_video_01.mp4","downloadId":"976c","errorCode":"0000","completed":false,"success":true,"toPath":"/data/data/com.smb3project/cache/","fromPath":"05262020_142454/","clientId":"0b0d","status":"downloading","message":"downloading","name":"downloadProgress"}
[Sat May 30 2020 01:38:47.190]  LOG      download progress data (on downloadProgress): {"downloadedSize":"204800","totalSize":"37793367","destPath":"/data/data/com.smb3project/cache/ch1_video_01.mp4","srcPath":"\\\\10.117.82.110\\fun2\\05262020_142454/","fileName":"ch1_video_01.mp4","downloadId":"976c","errorCode":"0000","completed":false,"success":true,"toPath":"/data/data/com.smb3project/cache/","fromPath":"05262020_142454/","clientId":"0b0d","status":"downloading","message":"downloading","name":"downloadProgress"}
[Sat May 30 2020 01:38:47.193]  LOG      download progress data (on downloadProgress): {"downloadedSize":"307200","totalSize":"37793367","destPath":"/data/data/com.smb3project/cache/ch1_video_01.mp4","srcPath":"\\\\10.117.82.110\\fun2\\05262020_142454/","fileName":"ch1_video_01.mp4","downloadId":"976c","errorCode":"0000","completed":false,"success":true,"toPath":"/data/data/com.smb3project/cache/","fromPath":"05262020_142454/","clientId":"0b0d","status":"downloading","message":"downloading","name":"downloadProgress"}
[Sat May 30 2020 01:38:47.194]  LOG      download progress data (on downloadProgress): {"downloadedSize":"409600","totalSize":"37793367","destPath":"/data/data/com.smb3project/cache/ch1_video_01.mp4","srcPath":"\\\\10.117.82.110\\fun2\\05262020_142454/","fileName":"ch1_video_01.mp4","downloadId":"976c","errorCode":"0000","completed":false,"success":true,"toPath":"/data/data/com.smb3project/cache/","fromPath":"05262020_142454/","clientId":"0b0d","status":"downloading","message":"downloading","name":"downloadProgress"}
[Sat May 30 2020 01:38:47.196]  LOG      download progress data (on downloadProgress): {"downloadedSize":"512000","totalSize":"37793367","destPath":"/data/data/com.smb3project/cache/ch1_video_01.mp4","srcPath":"\\\\10.117.82.110\\fun2\\05262020_142454/","fileName":"ch1_video_01.mp4","downloadId":"976c","errorCode":"0000","completed":false,"success":true,"toPath":"/data/data/com.smb3project/cache/","fromPath":"05262020_142454/","clientId":"0b0d","status":"downloading","message":"downloading","name":"downloadProgress"}
[Sat May 30 2020 01:38:47.257]  LOG      download progress data (on downloadProgress): {"downloadedSize":"614400","totalSize":"37793367","destPath":"/data/data/com.smb3project/cache/ch1_video_01.mp4","srcPath":"\\\\10.117.82.110\\fun2\\05262020_142454/","fileName":"ch1_video_01.mp4","downloadId":"976c","errorCode":"0000","completed":false,"success":true,"toPath":"/data/data/com.smb3project/cache/","fromPath":"05262020_142454/","clientId":"0b0d","status":"downloading","message":"downloading","name":"downloadProgress"}
[Sat May 30 2020 01:38:47.258]  LOG      download progress data (on downloadProgress): {"downloadedSize":"716800","totalSize":"37793367","destPath":"/data/data/com.smb3project/cache/ch1_video_01.mp4","srcPath":"\\\\10.117.82.110\\fun2\\05262020_142454/","fileName":"ch1_video_01.mp4","downloadId":"976c","errorCode":"0000","completed":false,"success":true,"toPath":"/data/data/com.smb3project/cache/","fromPath":"05262020_142454/","clientId":"0b0d","status":"canceled","message":"download canceled","name":"downloadProgress"}

Please let me know how to resolve this issue....

**Comment by kheravarun08** [comment]
I am trying to save video at the following path in android App folder :

/data/data/package/files/

**Comment by bodaghialib4** [comment]
Could you give me some information about your code?
It seems you cancel download or disconnect connection before finishing download.

**Comment by kheravarun08** [comment]
Yes you are correct I was canceling the download during download and that is why the issue was present .
It works perfectly.
Thanks for quick help.
