### ISSUE TITLE
Thanks for the wonderful library for SMB.It works like a charm on android platform.There is some build settings issue regarding s.hompage........

### ISSUE THREAD

**Issue by kheravarun08** [bodaghialib4/react-native-smb#4]

**Comment by bodaghialib4** [comment]
I could not understand the problem.
Could you please describe a little more detail?

**Comment by kheravarun08** [comment]
Hi,
I am getting this error when I integrate the library :

[!] The `RNReactNativeSmb` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is equal to the summary.

This error is as 'homepage' spec is not set for this library.Kindly set it so that is compiles with latest code

**Comment by bodaghialib4** [comment]
It seems the error related to iOS (which not support in this library).

I deleted the ios part (ios folder)  of the library in develop branch.

Could you please test my change in develop branch:
(by specifying `react-native-smb` git repository URL in package.json) 
```
 "dependencies": {
    ...
    "react-native-smb": "git://github.com/bodaghialib4/react-native-smb.git#develop"
    ...
  },
```

Please make me aware of the result of my change.

If the problem not fixed, please give me more information about your test environment.
- your testing platform (android/ios)
- your versions (RN, npm, android, etc )
- ...
- and a process to repeat this error in my system.

**Comment by kheravarun08** [comment]
Thanks for the help it is working perfectly now .....I would suggest please add this in read me file or on the main page so that people are able to use your wonderful library....

**Comment by bodaghialib4** [comment]
Thanks a lot.

No need for change in the readme file. 
I released my new changes in the new version (0.2.4).

Please change the package.json to use the newly released version:

```
 "dependencies": {
    ...
    "react-native-smb": "^0.2.4"
    ...
  },
```
or run `npm install react-native-smb --save` to use the new version.

If there is any problem, please make me aware. thanks.

**Comment by kheravarun08** [comment]
HI,
Your code was working fine till now but suddenly I got this error

exception in connecting server url: STATUS_LOGON_FAILURE (0xc000006d):
Authentication failed for '' using
***@***.***


I dont know why but it is not connecting via SMB.


Could you please look into this ASAP


Regards,

Varun Khera

**Comment by bodaghialib4** [comment]
It seems this is an Authentication error. Check your server is accessable. and also check your Authentication info.

if the error not solved, please create a new issue with some more info for this new error.

**Comment by bodaghialib4** [comment]
> HI, Your code was working fine till now but suddenly I got this error exception in connecting server url: STATUS_LOGON_FAILURE (0xc000006d): Authentication failed for '' using ***@***.*** I dont know why but it is not connecting via SMB. Could you please look into this ASAP Regards, Varun Khera
> […](#)

Is this related to issue #5?

**Comment by kheravarun08** [comment]
Its working nnow thanks for immediate help..
Server was fine but I think issue with mobile...I reset the mobile and it
worked...
