### ISSUE TITLE
Issue regarding SMB Connection

### ISSUE THREAD

**Issue by kheravarun08** [bodaghialib4/react-native-smb#5]
Hi,
I am somehow getting this error recently although the code was working perfectly previously :

com.hierynomus.mssmb2.SMBApiException: STATUS_LOGON_FAILURE (0xc000006d): Authentication failed for '' using com.hierynomus.smbj.auth.NtlmAuthenticator@6f7dd67
        at com.hierynomus.smbj.connection.Connection.authenticate

Regards,
Varun Khera

**Comment by bodaghialib4** [comment]
It seems this is an Authentication error. Could you please check your server is accessible and also your Authentication info?

If they are correct, please give some more info about your implementation.

**Comment by kheravarun08** [comment]
There was problem in the SMB configuration that is why I was getting the error.The library works perfectly
